# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice',
            field=models.TextField(default=''),
        ),
    ]
