# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20170722_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
